[profile.default]
solc_version = "0.8.27"
evm_version = "cancun"

optimizer = true
optimizer_runs = 9999

via_ir = true

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://rpc.ankr.com/eth"
base = "https://base.api.onfinality.io/public"
poly = "https://rpc.ankr.com/polygon"
opti = "https://mainnet.optimism.io"
arbi = "https://arb1.arbitrum.io/rpc"